# Generated by Django 5.0.7 on 2024-07-24 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='label',
            new_name='designation',
        ),
    ]
