# Generated by Django 5.0.7 on 2024-07-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0006_prospects'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prospects',
            options={'verbose_name': 'Prospect', 'verbose_name_plural': 'Prospects'},
        ),
        migrations.AddField(
            model_name='prospects',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='prospects',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
