# Generated by Django 5.0.7 on 2024-08-02 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0008_opportunites'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospects',
            name='observation',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='prospects',
            name='type_prospect',
            field=models.CharField(blank=True, choices=[('Entreprise', 'Entreprise'), ('Particulier', 'Particulier')], max_length=100, null=True),
        ),
    ]
