# Generated by Django 5.0.7 on 2024-08-02 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0009_prospects_observation_alter_prospects_type_prospect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospects',
            name='type_prospect',
            field=models.CharField(blank=True, choices=[('Particulier', 'Particulier'), ('Entreprise', 'Entreprise')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Rappels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_rappel', models.CharField(blank=True, choices=[('tel', 'Appel téléphonique'), ('ema', 'Email'), ('mes', 'Message')], max_length=3, null=True)),
                ('date_rappel', models.DateField(blank=True, null=True)),
                ('observation', models.CharField(blank=True, max_length=1000, null=True)),
                ('etat', models.CharField(blank=True, choices=[('enc', 'En cours'), ('fin', 'Terminer'), ('ann', 'Annuler'), ('att', 'En attente')], max_length=3, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercial.prospects')),
            ],
            options={
                'verbose_name': 'Rappel',
                'verbose_name_plural': 'Rappels',
            },
        ),
    ]
