# Generated by Django 5.0.7 on 2024-08-03 13:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0010_alter_prospects_type_prospect_rappels'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devis',
            options={'verbose_name': 'Devis', 'verbose_name_plural': 'Devis'},
        ),
        migrations.AddField(
            model_name='devis',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='commercial.clients'),
        ),
        migrations.AddField(
            model_name='devis',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devis',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('vir', 'Virement Bancaire'), ('esp', 'Espéce'), ('chq', 'Chéque')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='devis',
            name='num',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='devis',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='prospects',
            name='type_prospect',
            field=models.CharField(blank=True, choices=[('Entreprise', 'Entreprise'), ('Particulier', 'Particulier')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rappels',
            name='etat',
            field=models.CharField(blank=True, choices=[('att', 'En attente'), ('fin', 'Terminer'), ('enc', 'En cours'), ('ann', 'Annuler')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='rappels',
            name='type_rappel',
            field=models.CharField(blank=True, choices=[('tel', 'Appel téléphonique'), ('mes', 'Message'), ('ema', 'Email')], max_length=3, null=True),
        ),
    ]
