# Generated by Django 5.0.7 on 2024-08-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0011_alter_devis_options_devis_client_devis_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devis',
            name='num',
        ),
        migrations.AddField(
            model_name='devis',
            name='number',
            field=models.CharField(blank=True, max_length=1000, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('chq', 'Chéque'), ('vir', 'Virement Bancaire'), ('esp', 'Espéce')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='rappels',
            name='etat',
            field=models.CharField(blank=True, choices=[('ann', 'Annuler'), ('enc', 'En cours'), ('fin', 'Terminer'), ('att', 'En attente')], max_length=3, null=True),
        ),
    ]
