# Generated by Django 5.0.7 on 2024-08-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0012_remove_devis_num_devis_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('vir', 'Virement Bancaire'), ('chq', 'Chéque'), ('esp', 'Espéce')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='rappels',
            name='etat',
            field=models.CharField(blank=True, choices=[('enc', 'En cours'), ('att', 'En attente'), ('ann', 'Annuler'), ('fin', 'Terminer')], max_length=3, null=True),
        ),
    ]
