# Generated by Django 5.0.7 on 2024-08-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0014_clients_type_client_alter_devis_mode_paiement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='reg_commerce',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fournisseurs',
            name='reg_commerce',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='type_client',
            field=models.CharField(blank=True, choices=[('ent', 'Entreprise'), ('par', 'Particulier')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('vir', 'Virement Bancaire'), ('chq', 'Chéque'), ('esp', 'Espéce')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='prospects',
            name='type_prospect',
            field=models.CharField(blank=True, choices=[('ent', 'Entreprise'), ('par', 'Particulier')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rappels',
            name='etat',
            field=models.CharField(blank=True, choices=[('att', 'En attente'), ('ann', 'Annuler'), ('enc', 'En cours'), ('fin', 'Terminer')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='rappels',
            name='type_rappel',
            field=models.CharField(blank=True, choices=[('mes', 'Message'), ('ema', 'Email'), ('tel', 'Appel téléphonique')], max_length=3, null=True),
        ),
    ]
