# Generated by Django 5.0.7 on 2024-08-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0018_rename_create_at_generalsettings_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='description',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('vir', 'Virement Bancaire'), ('esp', 'Espéce'), ('chq', 'Chéque')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='devise',
            field=models.CharField(blank=True, choices=[('DEU', 'Allemagne'), ('SAU', 'Arabie Saoudite'), ('AND', 'Andorre'), ('ATG', 'Antigua-et-Barbuda'), ('ALB', 'Albanie'), ('ZAF', 'Afrique du Sud'), ('AGO', 'Angola'), ('AFG', 'Afghanistan'), ('DZA', 'Algérie')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='rappels',
            name='etat',
            field=models.CharField(blank=True, choices=[('ann', 'Annuler'), ('enc', 'En cours'), ('att', 'En attente'), ('fin', 'Terminer')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='rappels',
            name='type_rappel',
            field=models.CharField(blank=True, choices=[('mes', 'Message'), ('ema', 'Email'), ('tel', 'Appel téléphonique')], max_length=3, null=True),
        ),
    ]
