# Generated by Django 5.0.7 on 2024-08-18 14:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0019_products_description_alter_devis_mode_paiement_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ligne_devis',
            options={'verbose_name': 'Ligne du devis', 'verbose_name_plural': 'Lignes du devis'},
        ),
        migrations.AddField(
            model_name='ligne_devis',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ligne_devis',
            name='devis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='commercial.devis'),
        ),
        migrations.AddField(
            model_name='ligne_devis',
            name='produit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='commercial.products'),
        ),
        migrations.AddField(
            model_name='ligne_devis',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='devise',
            field=models.CharField(blank=True, choices=[('AND', 'Andorre'), ('DZA', 'Algérie'), ('ATG', 'Antigua-et-Barbuda'), ('ALB', 'Albanie'), ('AGO', 'Angola'), ('DEU', 'Allemagne'), ('ZAF', 'Afrique du Sud'), ('AFG', 'Afghanistan'), ('SAU', 'Arabie Saoudite')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='rappels',
            name='etat',
            field=models.CharField(blank=True, choices=[('att', 'En attente'), ('fin', 'Terminer'), ('ann', 'Annuler'), ('enc', 'En cours')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='rappels',
            name='type_rappel',
            field=models.CharField(blank=True, choices=[('ema', 'Email'), ('mes', 'Message'), ('tel', 'Appel téléphonique')], max_length=3, null=True),
        ),
    ]
