# Generated by Django 5.0.7 on 2024-08-19 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0021_alter_clients_type_client_alter_devis_mode_paiement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rappels',
            name='priority',
            field=models.CharField(blank=True, choices=[('me', 'Medium'), ('lo', 'Basse'), ('he', 'Haute')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('chq', 'Chéque'), ('vir', 'Virement Bancaire'), ('esp', 'Espéce')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='devise',
            field=models.CharField(blank=True, choices=[('ALB', 'Albanie'), ('ZAF', 'Afrique du Sud'), ('AGO', 'Angola'), ('ATG', 'Antigua-et-Barbuda'), ('AFG', 'Afghanistan'), ('AND', 'Andorre'), ('SAU', 'Arabie Saoudite'), ('DZA', 'Algérie'), ('DEU', 'Allemagne')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='rappels',
            name='etat',
            field=models.CharField(blank=True, choices=[('enc', 'En cours'), ('fin', 'Terminer'), ('ann', 'Annuler'), ('att', 'En attente')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='rappels',
            name='type_rappel',
            field=models.CharField(blank=True, choices=[('tel', 'Appel téléphonique'), ('mes', 'Message'), ('ema', 'Email')], max_length=3, null=True),
        ),
    ]
