# Generated by Django 5.0.7 on 2024-08-19 10:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0027_rappels_user_alter_clients_type_client_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mouvements_produit',
            options={'verbose_name': "Mouvement d'un produit", 'verbose_name_plural': 'Mouvements des produits'},
        ),
        migrations.AddField(
            model_name='mouvements_produit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mouvements_produit',
            name='produit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commercial.products'),
        ),
        migrations.AddField(
            model_name='mouvements_produit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mouvements_produit',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='devis',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('esp', 'Espéce'), ('chq', 'Chéque'), ('vir', 'Virement Bancaire')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='devise',
            field=models.CharField(blank=True, choices=[('AGO', 'Angola'), ('ATG', 'Antigua-et-Barbuda'), ('ZAF', 'Afrique du Sud'), ('AND', 'Andorre'), ('DZA', 'Algérie'), ('DEU', 'Allemagne'), ('ALB', 'Albanie'), ('AFG', 'Afghanistan'), ('SAU', 'Arabie Saoudite')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='rappels',
            name='etat',
            field=models.CharField(blank=True, choices=[('fin', 'Terminer'), ('ann', 'Annuler'), ('enc', 'En cours'), ('att', 'En attente')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='rappels',
            name='type_rappel',
            field=models.CharField(blank=True, choices=[('tel', 'Appel téléphonique'), ('ema', 'Email'), ('mes', 'Message')], max_length=3, null=True),
        ),
    ]
