# Generated by Django 5.0.7 on 2024-08-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0029_mouvements_produit_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvements_produit',
            name='qty',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('vir', 'Virement Bancaire'), ('chq', 'Chéque'), ('esp', 'Espéce')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='devise',
            field=models.CharField(blank=True, choices=[('DZA', 'Algérie'), ('ZAF', 'Afrique du Sud'), ('ALB', 'Albanie'), ('ATG', 'Antigua-et-Barbuda'), ('AFG', 'Afghanistan'), ('SAU', 'Arabie Saoudite'), ('AGO', 'Angola'), ('AND', 'Andorre'), ('DEU', 'Allemagne')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='mouvements_produit',
            name='type_mouvement',
            field=models.CharField(blank=True, choices=[('sor', 'Sortie'), ('ent', 'Entrée')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='rappels',
            name='etat',
            field=models.CharField(blank=True, choices=[('enc', 'En cours'), ('att', 'En attente'), ('ann', 'Annuler'), ('fin', 'Terminer')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='rappels',
            name='priority',
            field=models.CharField(blank=True, choices=[('he', 'Haute'), ('me', 'Medium'), ('lo', 'Basse')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='rappels',
            name='type_rappel',
            field=models.CharField(blank=True, choices=[('ema', 'Email'), ('tel', 'Appel téléphonique'), ('mes', 'Message')], max_length=3, null=True),
        ),
    ]
