# Generated by Django 5.0.7 on 2024-08-20 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0031_alter_clients_type_client_alter_devis_mode_paiement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsettings',
            name='devise',
            field=models.CharField(blank=True, choices=[('AGO', 'Angola'), ('DZA', 'Algérie'), ('AFG', 'Afghanistan'), ('ATG', 'Antigua-et-Barbuda'), ('ZAF', 'Afrique du Sud'), ('ALB', 'Albanie'), ('SAU', 'Arabie Saoudite'), ('DEU', 'Allemagne'), ('AND', 'Andorre')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='rappels',
            name='etat',
            field=models.CharField(blank=True, choices=[('ann', 'Annuler'), ('fin', 'Terminer'), ('enc', 'En cours'), ('att', 'En attente')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='rappels',
            name='priority',
            field=models.CharField(blank=True, choices=[('me', 'Medium'), ('he', 'Haute'), ('lo', 'Basse')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='rappels',
            name='type_rappel',
            field=models.CharField(blank=True, choices=[('ema', 'Email'), ('mes', 'Message'), ('tel', 'Appel téléphonique')], max_length=3, null=True),
        ),
        migrations.CreateModel(
            name='LigneCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caisse', models.CharField(blank=True, max_length=100, null=True)),
                ('qty', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commercial.products')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ligne caisse',
                'verbose_name_plural': 'Lignes caisse',
            },
        ),
    ]
