# Generated by Django 5.0.7 on 2024-08-21 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0036_alter_devis_mode_paiement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignecaisse',
            name='prix_vente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='type_client',
            field=models.CharField(blank=True, choices=[('par', 'Particulier'), ('ent', 'Entreprise')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='devise',
            field=models.CharField(blank=True, choices=[('DEU', 'Allemagne'), ('DZA', 'Algérie'), ('ZAF', 'Afrique du Sud'), ('AFG', 'Afghanistan'), ('ATG', 'Antigua-et-Barbuda'), ('AGO', 'Angola'), ('AND', 'Andorre'), ('ALB', 'Albanie'), ('SAU', 'Arabie Saoudite')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='prospects',
            name='type_prospect',
            field=models.CharField(blank=True, choices=[('par', 'Particulier'), ('ent', 'Entreprise')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rappels',
            name='etat',
            field=models.CharField(blank=True, choices=[('fin', 'Terminer'), ('enc', 'En cours'), ('att', 'En attente'), ('ann', 'Annuler')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='rappels',
            name='priority',
            field=models.CharField(blank=True, choices=[('me', 'Medium'), ('lo', 'Basse'), ('he', 'Haute')], max_length=2, null=True),
        ),
    ]
