# Generated by Django 5.0.7 on 2024-08-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0037_lignecaisse_prix_vente_alter_clients_type_client_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generalsettings',
            options={'verbose_name': 'Configuration', 'verbose_name_plural': 'Configuration'},
        ),
        migrations.AddField(
            model_name='lignecaisse',
            name='montant_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='devise',
            field=models.CharField(blank=True, choices=[('AND', 'Andorre'), ('AGO', 'Angola'), ('ZAF', 'Afrique du Sud'), ('ATG', 'Antigua-et-Barbuda'), ('ALB', 'Albanie'), ('DEU', 'Allemagne'), ('DZA', 'Algérie'), ('SAU', 'Arabie Saoudite'), ('AFG', 'Afghanistan')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='mouvements_produit',
            name='type_mouvement',
            field=models.CharField(blank=True, choices=[('sor', 'Sortie'), ('ent', 'Entrée')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='rappels',
            name='etat',
            field=models.CharField(blank=True, choices=[('ann', 'Annuler'), ('att', 'En attente'), ('fin', 'Terminer'), ('enc', 'En cours')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='rappels',
            name='priority',
            field=models.CharField(blank=True, choices=[('lo', 'Basse'), ('he', 'Haute'), ('me', 'Medium')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='rappels',
            name='type_rappel',
            field=models.CharField(blank=True, choices=[('mes', 'Message'), ('tel', 'Appel téléphonique'), ('ema', 'Email')], max_length=3, null=True),
        ),
    ]
