# Generated by Django 5.0.7 on 2024-08-22 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0038_alter_generalsettings_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsettings',
            name='devise',
            field=models.CharField(blank=True, choices=[('AFG', 'Afghanistan'), ('ZAF', 'Afrique du Sud'), ('ALB', 'Albanie'), ('ATG', 'Antigua-et-Barbuda'), ('AGO', 'Angola'), ('AND', 'Andorre'), ('SAU', 'Arabie Saoudite'), ('DZA', 'Algérie'), ('DEU', 'Allemagne')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='lignecaisse',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commercial.sessionvente'),
        ),
        migrations.AlterField(
            model_name='rappels',
            name='etat',
            field=models.CharField(blank=True, choices=[('enc', 'En cours'), ('ann', 'Annuler'), ('fin', 'Terminer'), ('att', 'En attente')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='rappels',
            name='priority',
            field=models.CharField(blank=True, choices=[('me', 'Medium'), ('lo', 'Basse'), ('he', 'Haute')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='rappels',
            name='type_rappel',
            field=models.CharField(blank=True, choices=[('tel', 'Appel téléphonique'), ('mes', 'Message'), ('ema', 'Email')], max_length=3, null=True),
        ),
    ]
