# Generated by Django 5.0.7 on 2024-08-25 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0042_profile_image_alter_devis_mode_paiement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='date_expiration',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devis',
            name='delai_paiement',
            field=models.CharField(blank=True, choices=[('rec', 'A réception'), ('imm', 'Immédiat'), ('30j', 'A 30 jours')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='devis',
            name='etat',
            field=models.CharField(blank=True, choices=[('bro', 'Brouillon'), ('ann', 'Annuller'), ('fac', 'Facturer')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='devis',
            name='observation',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='devis',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clients',
            name='type_client',
            field=models.CharField(blank=True, choices=[('par', 'Particulier'), ('ent', 'Entreprise')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='devise',
            field=models.CharField(blank=True, choices=[('DZA', 'Algérie'), ('ZAF', 'Afrique du Sud'), ('SAU', 'Arabie Saoudite'), ('DEU', 'Allemagne'), ('AFG', 'Afghanistan'), ('AND', 'Andorre'), ('ATG', 'Antigua-et-Barbuda'), ('AGO', 'Angola'), ('ALB', 'Albanie')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='mouvements_produit',
            name='type_mouvement',
            field=models.CharField(blank=True, choices=[('sor', 'Sortie'), ('ent', 'Entrée')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='prospects',
            name='type_prospect',
            field=models.CharField(blank=True, choices=[('par', 'Particulier'), ('ent', 'Entreprise')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rappels',
            name='etat',
            field=models.CharField(blank=True, choices=[('att', 'En attente'), ('fin', 'Terminer'), ('enc', 'En cours'), ('ann', 'Annuler')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='rappels',
            name='priority',
            field=models.CharField(blank=True, choices=[('me', 'Medium'), ('lo', 'Basse'), ('he', 'Haute')], max_length=2, null=True),
        ),
    ]
