# Generated by Django 5.0.7 on 2024-08-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0043_devis_date_expiration_devis_delai_paiement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('taux', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Taux',
                'verbose_name_plural': 'Taux TVA',
            },
        ),
        migrations.AlterField(
            model_name='clients',
            name='type_client',
            field=models.CharField(blank=True, choices=[('ent', 'Entreprise'), ('par', 'Particulier')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='etat',
            field=models.CharField(blank=True, choices=[('fac', 'Facturer'), ('ann', 'Annuller'), ('bro', 'Brouillon')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('vir', 'Virement Bancaire'), ('chq', 'Chéque'), ('esp', 'Espéce')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='devise',
            field=models.CharField(blank=True, choices=[('DZA', 'Algérie'), ('AFG', 'Afghanistan'), ('AND', 'Andorre'), ('ATG', 'Antigua-et-Barbuda'), ('ALB', 'Albanie'), ('SAU', 'Arabie Saoudite'), ('DEU', 'Allemagne'), ('AGO', 'Angola'), ('ZAF', 'Afrique du Sud')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='mouvements_produit',
            name='type_mouvement',
            field=models.CharField(blank=True, choices=[('ent', 'Entrée'), ('sor', 'Sortie')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type_profile',
            field=models.CharField(blank=True, choices=[('ven', 'Vendeurs'), ('adm', 'Administrateur')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='prospects',
            name='type_prospect',
            field=models.CharField(blank=True, choices=[('ent', 'Entreprise'), ('par', 'Particulier')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rappels',
            name='etat',
            field=models.CharField(blank=True, choices=[('ann', 'Annuler'), ('enc', 'En cours'), ('fin', 'Terminer'), ('att', 'En attente')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='rappels',
            name='type_rappel',
            field=models.CharField(blank=True, choices=[('ema', 'Email'), ('mes', 'Message'), ('tel', 'Appel téléphonique')], max_length=3, null=True),
        ),
    ]
