# Generated by Django 5.0.7 on 2024-08-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0044_tva_alter_clients_type_client_alter_devis_etat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='date_devis',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='type_client',
            field=models.CharField(blank=True, choices=[('par', 'Particulier'), ('ent', 'Entreprise')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='delai_paiement',
            field=models.CharField(blank=True, choices=[('30j', 'A 30 jours'), ('rec', 'A réception'), ('imm', 'Immédiat')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='etat',
            field=models.CharField(blank=True, choices=[('ann', 'Annuller'), ('fac', 'Facturer'), ('bro', 'Brouillon')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('esp', 'Espéce'), ('vir', 'Virement Bancaire'), ('chq', 'Chéque')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='devise',
            field=models.CharField(blank=True, choices=[('SAU', 'Arabie Saoudite'), ('ZAF', 'Afrique du Sud'), ('AGO', 'Angola'), ('ATG', 'Antigua-et-Barbuda'), ('DEU', 'Allemagne'), ('ALB', 'Albanie'), ('AND', 'Andorre'), ('AFG', 'Afghanistan'), ('DZA', 'Algérie')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='mouvements_produit',
            name='type_mouvement',
            field=models.CharField(blank=True, choices=[('sor', 'Sortie'), ('ent', 'Entrée')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type_profile',
            field=models.CharField(blank=True, choices=[('adm', 'Administrateur'), ('ven', 'Vendeurs')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='prospects',
            name='type_prospect',
            field=models.CharField(blank=True, choices=[('par', 'Particulier'), ('ent', 'Entreprise')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rappels',
            name='etat',
            field=models.CharField(blank=True, choices=[('att', 'En attente'), ('ann', 'Annuler'), ('fin', 'Terminer'), ('enc', 'En cours')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='rappels',
            name='priority',
            field=models.CharField(blank=True, choices=[('he', 'Haute'), ('me', 'Medium'), ('lo', 'Basse')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='rappels',
            name='type_rappel',
            field=models.CharField(blank=True, choices=[('tel', 'Appel téléphonique'), ('ema', 'Email'), ('mes', 'Message')], max_length=3, null=True),
        ),
    ]
