# Generated by Django 5.0.7 on 2024-08-27 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0047_alter_clients_type_client_alter_devis_delai_paiement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligne_devis',
            name='ht',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ligne_devis',
            name='ttc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ligne_devis',
            name='tva',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='delai_paiement',
            field=models.CharField(blank=True, choices=[('30j', 'A 30 jours'), ('rec', 'A réception'), ('imm', 'Immédiat')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='etat',
            field=models.CharField(blank=True, choices=[('fac', 'A facturé'), ('ann', 'Annulé'), ('bro', 'Brouillon')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='devise',
            field=models.CharField(blank=True, choices=[('AFG', 'Afghanistan'), ('DEU', 'Allemagne'), ('DZA', 'Algérie'), ('ALB', 'Albanie'), ('AGO', 'Angola'), ('AND', 'Andorre'), ('ATG', 'Antigua-et-Barbuda'), ('SAU', 'Arabie Saoudite'), ('ZAF', 'Afrique du Sud')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='mouvements_produit',
            name='type_mouvement',
            field=models.CharField(blank=True, choices=[('sor', 'Sortie'), ('ent', 'Entrée')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='rappels',
            name='etat',
            field=models.CharField(blank=True, choices=[('att', 'En attente'), ('enc', 'En cours'), ('ann', 'Annuler'), ('fin', 'Terminer')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='rappels',
            name='priority',
            field=models.CharField(blank=True, choices=[('me', 'Medium'), ('he', 'Haute'), ('lo', 'Basse')], max_length=2, null=True),
        ),
    ]
