# Generated by Django 5.0.7 on 2024-08-27 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0048_ligne_devis_ht_ligne_devis_ttc_ligne_devis_tva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis',
            name='delai_paiement',
            field=models.CharField(blank=True, choices=[('imm', 'Immédiat'), ('rec', 'A réception'), ('30j', 'A 30 jours')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='etat',
            field=models.CharField(blank=True, choices=[('fac', 'A facturé'), ('ann', 'Annulé'), ('ter', 'Terminer'), ('bro', 'Brouillon')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('esp', 'Espéce'), ('vir', 'Virement Bancaire'), ('chq', 'Chéque')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='devise',
            field=models.CharField(blank=True, choices=[('ALB', 'Albanie'), ('DEU', 'Allemagne'), ('ZAF', 'Afrique du Sud'), ('SAU', 'Arabie Saoudite'), ('AGO', 'Angola'), ('AND', 'Andorre'), ('DZA', 'Algérie'), ('ATG', 'Antigua-et-Barbuda'), ('AFG', 'Afghanistan')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='mouvements_produit',
            name='type_mouvement',
            field=models.CharField(blank=True, choices=[('ent', 'Entrée'), ('sor', 'Sortie')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='rappels',
            name='etat',
            field=models.CharField(blank=True, choices=[('att', 'En attente'), ('fin', 'Terminer'), ('ann', 'Annuler'), ('enc', 'En cours')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='rappels',
            name='priority',
            field=models.CharField(blank=True, choices=[('he', 'Haute'), ('me', 'Medium'), ('lo', 'Basse')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='rappels',
            name='type_rappel',
            field=models.CharField(blank=True, choices=[('tel', 'Appel téléphonique'), ('mes', 'Message'), ('ema', 'Email')], max_length=3, null=True),
        ),
    ]
