# Generated by Django 5.0.7 on 2024-08-27 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0049_alter_devis_delai_paiement_alter_devis_etat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infos_Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Ligne_Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='clients',
            name='type_client',
            field=models.CharField(blank=True, choices=[('par', 'Particulier'), ('ent', 'Entreprise')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='delai_paiement',
            field=models.CharField(blank=True, choices=[('rec', 'A réception'), ('30j', 'A 30 jours'), ('imm', 'Immédiat')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='etat',
            field=models.CharField(blank=True, choices=[('bro', 'Brouillon'), ('fac', 'A facturé'), ('ann', 'Annulé'), ('ter', 'Terminer')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('chq', 'Chéque'), ('vir', 'Virement Bancaire'), ('esp', 'Espéce')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='devise',
            field=models.CharField(blank=True, choices=[('SAU', 'Arabie Saoudite'), ('AND', 'Andorre'), ('AGO', 'Angola'), ('ALB', 'Albanie'), ('DEU', 'Allemagne'), ('DZA', 'Algérie'), ('AFG', 'Afghanistan'), ('ATG', 'Antigua-et-Barbuda'), ('ZAF', 'Afrique du Sud')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='mouvements_produit',
            name='type_mouvement',
            field=models.CharField(blank=True, choices=[('sor', 'Sortie'), ('ent', 'Entrée')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type_profile',
            field=models.CharField(blank=True, choices=[('ven', 'Vendeurs'), ('adm', 'Administrateur')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='prospects',
            name='type_prospect',
            field=models.CharField(blank=True, choices=[('par', 'Particulier'), ('ent', 'Entreprise')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rappels',
            name='etat',
            field=models.CharField(blank=True, choices=[('enc', 'En cours'), ('ann', 'Annuler'), ('att', 'En attente'), ('fin', 'Terminer')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='rappels',
            name='priority',
            field=models.CharField(blank=True, choices=[('lo', 'Basse'), ('he', 'Haute'), ('me', 'Medium')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='rappels',
            name='type_rappel',
            field=models.CharField(blank=True, choices=[('mes', 'Message'), ('tel', 'Appel téléphonique'), ('ema', 'Email')], max_length=3, null=True),
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=1000, null=True, unique=True)),
                ('date_facturation', models.DateField(blank=True, null=True)),
                ('mode_paiement', models.CharField(blank=True, choices=[('chq', 'Chéque'), ('vir', 'Virement Bancaire'), ('esp', 'Espéce')], max_length=3, null=True)),
                ('delai_paiement', models.CharField(blank=True, choices=[('rec', 'A réception'), ('30j', 'A 30 jours'), ('imm', 'Immédiat')], max_length=3, null=True)),
                ('etat', models.CharField(blank=True, choices=[('bro', 'Brouillon'), ('fac', 'A facturé'), ('ann', 'Annulé'), ('ter', 'Terminer')], max_length=3, null=True)),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('observation', models.TextField(blank=True, max_length=3000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commercial.clients')),
                ('devis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commercial.devis')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
            },
        ),
    ]
