# Generated by Django 5.0.7 on 2024-08-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0053_facture_montant_ht_facture_montant_paye_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infos_entreprise',
            options={'verbose_name': 'Mon Entreprise'},
        ),
        migrations.AddField(
            model_name='infos_entreprise',
            name='adresse',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='infos_entreprise',
            name='art',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='infos_entreprise',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='infos_entreprise',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='infos_entreprise',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='infos_entreprise',
            name='fax',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='infos_entreprise',
            name='iban',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='infos_entreprise',
            name='mobile',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='infos_entreprise',
            name='nif',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='infos_entreprise',
            name='nis',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='infos_entreprise',
            name='reg_commerce',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='infos_entreprise',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='type_client',
            field=models.CharField(blank=True, choices=[('ent', 'Entreprise'), ('par', 'Particulier')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='etat',
            field=models.CharField(blank=True, choices=[('ter', 'Terminer'), ('fac', 'A facturé'), ('ann', 'Annulé'), ('bro', 'Brouillon')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('vir', 'Virement Bancaire'), ('chq', 'Chéque'), ('esp', 'Espéce')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='etat',
            field=models.CharField(blank=True, choices=[('ter', 'Terminer'), ('fac', 'A facturé'), ('ann', 'Annulé'), ('bro', 'Brouillon')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('vir', 'Virement Bancaire'), ('chq', 'Chéque'), ('esp', 'Espéce')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='devise',
            field=models.CharField(blank=True, choices=[('ALB', 'Albanie'), ('SAU', 'Arabie Saoudite'), ('ZAF', 'Afrique du Sud'), ('DZA', 'Algérie'), ('AFG', 'Afghanistan'), ('DEU', 'Allemagne'), ('AND', 'Andorre'), ('AGO', 'Angola'), ('ATG', 'Antigua-et-Barbuda')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type_profile',
            field=models.CharField(blank=True, choices=[('ven', 'Vendeurs'), ('adm', 'Administrateur')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='prospects',
            name='type_prospect',
            field=models.CharField(blank=True, choices=[('ent', 'Entreprise'), ('par', 'Particulier')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rappels',
            name='etat',
            field=models.CharField(blank=True, choices=[('fin', 'Terminer'), ('att', 'En attente'), ('enc', 'En cours'), ('ann', 'Annuler')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='rappels',
            name='priority',
            field=models.CharField(blank=True, choices=[('lo', 'Basse'), ('he', 'Haute'), ('me', 'Medium')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='rappels',
            name='type_rappel',
            field=models.CharField(blank=True, choices=[('ema', 'Email'), ('mes', 'Message'), ('tel', 'Appel téléphonique')], max_length=3, null=True),
        ),
    ]
