# Generated by Django 5.0.7 on 2024-08-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0055_facture_avoir_remove_facture_date_expiration_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paiementclient',
            options={'verbose_name': 'Paiement facture', 'verbose_name_plural': 'Paiements facture'},
        ),
        migrations.AlterField(
            model_name='devis',
            name='delai_paiement',
            field=models.CharField(blank=True, choices=[('30j', 'A 30 jours'), ('rec', 'A réception'), ('imm', 'Immédiat')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='etat',
            field=models.CharField(blank=True, choices=[('fac', 'A facturé'), ('bro', 'Brouillon'), ('ann', 'Annulé'), ('ter', 'Terminer')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('vir', 'Virement Bancaire'), ('esp', 'Espéce'), ('chq', 'Chéque')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='delai_paiement',
            field=models.CharField(blank=True, choices=[('30j', 'A 30 jours'), ('rec', 'A réception'), ('imm', 'Immédiat')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='etat',
            field=models.CharField(blank=True, choices=[('fac', 'A facturé'), ('bro', 'Brouillon'), ('ann', 'Annulé'), ('ter', 'Terminer')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('vir', 'Virement Bancaire'), ('esp', 'Espéce'), ('chq', 'Chéque')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='devise',
            field=models.CharField(blank=True, choices=[('ALB', 'Albanie'), ('AGO', 'Angola'), ('DEU', 'Allemagne'), ('SAU', 'Arabie Saoudite'), ('AND', 'Andorre'), ('AFG', 'Afghanistan'), ('DZA', 'Algérie'), ('ATG', 'Antigua-et-Barbuda'), ('ZAF', 'Afrique du Sud')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='mouvements_produit',
            name='type_mouvement',
            field=models.CharField(blank=True, choices=[('ent', 'Entrée'), ('sor', 'Sortie')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='paiementclient',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('vir', 'Virement Bancaire'), ('esp', 'Espéce'), ('chq', 'Chéque')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type_profile',
            field=models.CharField(blank=True, choices=[('adm', 'Administrateur'), ('ven', 'Vendeurs')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='rappels',
            name='etat',
            field=models.CharField(blank=True, choices=[('ann', 'Annuler'), ('enc', 'En cours'), ('att', 'En attente'), ('fin', 'Terminer')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='rappels',
            name='priority',
            field=models.CharField(blank=True, choices=[('he', 'Haute'), ('me', 'Medium'), ('lo', 'Basse')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='rappels',
            name='type_rappel',
            field=models.CharField(blank=True, choices=[('ema', 'Email'), ('mes', 'Message'), ('tel', 'Appel téléphonique')], max_length=3, null=True),
        ),
    ]
