# Generated by Django 5.0.7 on 2024-09-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0059_stock_stock_alert_alter_clients_type_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='stock_alert',
        ),
        migrations.AddField(
            model_name='products',
            name='stock_alert',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='type_client',
            field=models.CharField(blank=True, choices=[('par', 'Particulier'), ('ent', 'Entreprise')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='delai_paiement',
            field=models.CharField(blank=True, choices=[('30j', 'A 30 jours'), ('imm', 'Immédiat'), ('rec', 'A réception')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='etat',
            field=models.CharField(blank=True, choices=[('ter', 'Terminer'), ('fac', 'A facturé'), ('bro', 'Brouillon'), ('ann', 'Annulé')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='delai_paiement',
            field=models.CharField(blank=True, choices=[('30j', 'A 30 jours'), ('imm', 'Immédiat'), ('rec', 'A réception')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='devise',
            field=models.CharField(blank=True, choices=[('SAU', 'Arabie Saoudite'), ('DEU', 'Allemagne'), ('ATG', 'Antigua-et-Barbuda'), ('AND', 'Andorre'), ('ALB', 'Albanie'), ('ZAF', 'Afrique du Sud'), ('AGO', 'Angola'), ('DZA', 'Algérie'), ('AFG', 'Afghanistan')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='mouvements_produit',
            name='type_mouvement',
            field=models.CharField(blank=True, choices=[('sor', 'Sortie'), ('ent', 'Entrée')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='prospects',
            name='type_prospect',
            field=models.CharField(blank=True, choices=[('par', 'Particulier'), ('ent', 'Entreprise')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rappels',
            name='etat',
            field=models.CharField(blank=True, choices=[('enc', 'En cours'), ('fin', 'Terminer'), ('ann', 'Annuler'), ('att', 'En attente')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='rappels',
            name='priority',
            field=models.CharField(blank=True, choices=[('lo', 'Basse'), ('me', 'Medium'), ('he', 'Haute')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='rappels',
            name='type_rappel',
            field=models.CharField(blank=True, choices=[('mes', 'Message'), ('ema', 'Email'), ('tel', 'Appel téléphonique')], max_length=3, null=True),
        ),
    ]
