# Generated by Django 5.0.7 on 2024-09-02 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0061_alter_devis_delai_paiement_alter_devis_etat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='type_client',
            field=models.CharField(blank=True, choices=[('ent', 'Entreprise'), ('par', 'Particulier')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='delai_paiement',
            field=models.CharField(blank=True, choices=[('30j', 'A 30 jours'), ('rec', 'A réception'), ('imm', 'Immédiat')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='etat',
            field=models.CharField(blank=True, choices=[('bro', 'Brouillon'), ('ter', 'Terminer'), ('ann', 'Annulé'), ('fac', 'A facturé')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('vir', 'Virement Bancaire'), ('chq', 'Chéque'), ('esp', 'Espéce')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='delai_paiement',
            field=models.CharField(blank=True, choices=[('30j', 'A 30 jours'), ('rec', 'A réception'), ('imm', 'Immédiat')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('vir', 'Virement Bancaire'), ('chq', 'Chéque'), ('esp', 'Espéce')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='devise',
            field=models.CharField(blank=True, choices=[('SAU', 'Arabie Saoudite'), ('ZAF', 'Afrique du Sud'), ('AGO', 'Angola'), ('DEU', 'Allemagne'), ('AND', 'Andorre'), ('ALB', 'Albanie'), ('AFG', 'Afghanistan'), ('DZA', 'Algérie'), ('ATG', 'Antigua-et-Barbuda')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='mouvements_produit',
            name='type_mouvement',
            field=models.CharField(blank=True, choices=[('sor', 'Sortie'), ('ent', 'Entrée')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='paiementclient',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('vir', 'Virement Bancaire'), ('chq', 'Chéque'), ('esp', 'Espéce')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='prospects',
            name='type_prospect',
            field=models.CharField(blank=True, choices=[('ent', 'Entreprise'), ('par', 'Particulier')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rappels',
            name='etat',
            field=models.CharField(blank=True, choices=[('enc', 'En cours'), ('fin', 'Terminer'), ('ann', 'Annuler'), ('att', 'En attente')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='rappels',
            name='priority',
            field=models.CharField(blank=True, choices=[('lo', 'Basse'), ('he', 'Haute'), ('me', 'Medium')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='rappels',
            name='type_rappel',
            field=models.CharField(blank=True, choices=[('ema', 'Email'), ('tel', 'Appel téléphonique'), ('mes', 'Message')], max_length=3, null=True),
        ),
    ]
