# Generated by Django 5.0.7 on 2024-09-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0063_products_type_produit_alter_devis_delai_paiement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='print_ticket_pdf',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='type_client',
            field=models.CharField(blank=True, choices=[('par', 'Particulier'), ('ent', 'Entreprise')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='delai_paiement',
            field=models.CharField(blank=True, choices=[('rec', 'A réception'), ('imm', 'Immédiat'), ('30j', 'A 30 jours')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='etat',
            field=models.CharField(blank=True, choices=[('fac', 'A facturé'), ('bro', 'Brouillon'), ('ann', 'Annulé'), ('ter', 'Terminer')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('chq', 'Chéque'), ('esp', 'Espéce'), ('vir', 'Virement Bancaire')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='delai_paiement',
            field=models.CharField(blank=True, choices=[('rec', 'A réception'), ('imm', 'Immédiat'), ('30j', 'A 30 jours')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('chq', 'Chéque'), ('esp', 'Espéce'), ('vir', 'Virement Bancaire')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='devise',
            field=models.CharField(blank=True, choices=[('AFG', 'Afghanistan'), ('DEU', 'Allemagne'), ('ATG', 'Antigua-et-Barbuda'), ('SAU', 'Arabie Saoudite'), ('ZAF', 'Afrique du Sud'), ('AGO', 'Angola'), ('ALB', 'Albanie'), ('DZA', 'Algérie'), ('AND', 'Andorre')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='mouvements_produit',
            name='type_mouvement',
            field=models.CharField(blank=True, choices=[('sor', 'Sortie'), ('ent', 'Entrée')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='paiementclient',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('chq', 'Chéque'), ('esp', 'Espéce'), ('vir', 'Virement Bancaire')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type_profile',
            field=models.CharField(blank=True, choices=[('adm', 'Administrateur'), ('ven', 'Vendeurs')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='prospects',
            name='type_prospect',
            field=models.CharField(blank=True, choices=[('par', 'Particulier'), ('ent', 'Entreprise')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rappels',
            name='etat',
            field=models.CharField(blank=True, choices=[('fin', 'Terminer'), ('att', 'En attente'), ('enc', 'En cours'), ('ann', 'Annuler')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='rappels',
            name='priority',
            field=models.CharField(blank=True, choices=[('he', 'Haute'), ('lo', 'Basse'), ('me', 'Medium')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='rappels',
            name='type_rappel',
            field=models.CharField(blank=True, choices=[('ema', 'Email'), ('tel', 'Appel téléphonique'), ('mes', 'Message')], max_length=3, null=True),
        ),
    ]
