# Generated by Django 5.0.7 on 2024-09-04 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0066_alter_lignefactureavoir_options_facture_avoir_etat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture_avoir',
            name='motifs',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='type_client',
            field=models.CharField(blank=True, choices=[('par', 'Particulier'), ('ent', 'Entreprise')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='delai_paiement',
            field=models.CharField(blank=True, choices=[('rec', 'A réception'), ('imm', 'Immédiat'), ('30j', 'A 30 jours')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='etat',
            field=models.CharField(blank=True, choices=[('fac', 'A facturé'), ('ter', 'Terminer'), ('ann', 'Annulé'), ('bro', 'Brouillon')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='delai_paiement',
            field=models.CharField(blank=True, choices=[('rec', 'A réception'), ('imm', 'Immédiat'), ('30j', 'A 30 jours')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='etat',
            field=models.CharField(blank=True, choices=[('ter', 'Terminer'), ('bro', 'Brouillon')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='facture_avoir',
            name='etat',
            field=models.CharField(blank=True, choices=[('ter', 'Terminer'), ('bro', 'Brouillon')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='facture_avoir',
            name='ref_facture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commercial.facture'),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='devise',
            field=models.CharField(blank=True, choices=[('SAU', 'Arabie Saoudite'), ('AND', 'Andorre'), ('ATG', 'Antigua-et-Barbuda'), ('ZAF', 'Afrique du Sud'), ('DZA', 'Algérie'), ('AFG', 'Afghanistan'), ('AGO', 'Angola'), ('DEU', 'Allemagne'), ('ALB', 'Albanie')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='type_produit',
            field=models.CharField(blank=True, choices=[('pro', 'Produit'), ('srv', 'Service')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='prospects',
            name='type_prospect',
            field=models.CharField(blank=True, choices=[('par', 'Particulier'), ('ent', 'Entreprise')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rappels',
            name='etat',
            field=models.CharField(blank=True, choices=[('ann', 'Annuler'), ('fin', 'Terminer'), ('enc', 'En cours'), ('att', 'En attente')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='rappels',
            name='priority',
            field=models.CharField(blank=True, choices=[('me', 'Medium'), ('lo', 'Basse'), ('he', 'Haute')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='rappels',
            name='type_rappel',
            field=models.CharField(blank=True, choices=[('tel', 'Appel téléphonique'), ('ema', 'Email'), ('mes', 'Message')], max_length=3, null=True),
        ),
    ]
