# Generated by Django 5.0.7 on 2024-09-18 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commercial", "0074_products_user_alter_clients_type_client_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="categorie_produit",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="devis",
            name="delai_paiement",
            field=models.CharField(
                blank=True,
                choices=[
                    ("rec", "A réception"),
                    ("30j", "A 30 jours"),
                    ("imm", "Immédiat"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="devis",
            name="etat",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ter", "Terminer"),
                    ("bro", "Brouillon"),
                    ("fac", "A facturé"),
                    ("ann", "Annulé"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="facture",
            name="delai_paiement",
            field=models.CharField(
                blank=True,
                choices=[
                    ("rec", "A réception"),
                    ("30j", "A 30 jours"),
                    ("imm", "Immédiat"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="facture",
            name="etat",
            field=models.CharField(
                blank=True,
                choices=[("bro", "Brouillon"), ("ter", "Terminer")],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="facture_avoir",
            name="etat",
            field=models.CharField(
                blank=True,
                choices=[("bro", "Brouillon"), ("ter", "Terminer")],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="generalsettings",
            name="devise",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ZAF", "Afrique du Sud"),
                    ("AFG", "Afghanistan"),
                    ("ALB", "Albanie"),
                    ("SAU", "Arabie Saoudite"),
                    ("AGO", "Angola"),
                    ("AND", "Andorre"),
                    ("DEU", "Allemagne"),
                    ("DZA", "Algérie"),
                    ("ATG", "Antigua-et-Barbuda"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="products",
            name="type_produit",
            field=models.CharField(
                blank=True,
                choices=[("srv", "Service"), ("pro", "Produit")],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="products",
            name="type_tarifcation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("a", "Année"),
                    ("m", "Mois"),
                    ("j", "Jour"),
                    ("h", "Horaire"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="type_profile",
            field=models.CharField(
                blank=True,
                choices=[("ven", "Vendeurs"), ("adm", "Administrateur")],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="rappels",
            name="etat",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ann", "Annuler"),
                    ("att", "En attente"),
                    ("fin", "Terminer"),
                    ("enc", "En cours"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="rappels",
            name="priority",
            field=models.CharField(
                blank=True,
                choices=[("he", "Haute"), ("me", "Medium"), ("lo", "Basse")],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="rappels",
            name="type_rappel",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mes", "Message"),
                    ("ema", "Email"),
                    ("tel", "Appel téléphonique"),
                ],
                max_length=3,
                null=True,
            ),
        ),
    ]
