# Generated by Django 5.0.7 on 2024-09-18 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "commercial",
            "0075_categorie_produit_user_alter_devis_delai_paiement_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="categorie_produit",
            name="description",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="devis",
            name="delai_paiement",
            field=models.CharField(
                blank=True,
                choices=[
                    ("30j", "A 30 jours"),
                    ("imm", "Immédiat"),
                    ("rec", "A réception"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="devis",
            name="etat",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ann", "Annulé"),
                    ("ter", "Terminer"),
                    ("bro", "Brouillon"),
                    ("fac", "A facturé"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="devis",
            name="mode_paiement",
            field=models.CharField(
                blank=True,
                choices=[
                    ("vir", "Virement Bancaire"),
                    ("esp", "Espéce"),
                    ("chq", "Chéque"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="facture",
            name="delai_paiement",
            field=models.CharField(
                blank=True,
                choices=[
                    ("30j", "A 30 jours"),
                    ("imm", "Immédiat"),
                    ("rec", "A réception"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="facture",
            name="mode_paiement",
            field=models.CharField(
                blank=True,
                choices=[
                    ("vir", "Virement Bancaire"),
                    ("esp", "Espéce"),
                    ("chq", "Chéque"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="generalsettings",
            name="devise",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ALB", "Albanie"),
                    ("AND", "Andorre"),
                    ("AFG", "Afghanistan"),
                    ("ZAF", "Afrique du Sud"),
                    ("AGO", "Angola"),
                    ("ATG", "Antigua-et-Barbuda"),
                    ("SAU", "Arabie Saoudite"),
                    ("DZA", "Algérie"),
                    ("DEU", "Allemagne"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="mouvements_produit",
            name="type_mouvement",
            field=models.CharField(
                blank=True,
                choices=[("ent", "Entrée"), ("sor", "Sortie")],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="paiementclient",
            name="mode_paiement",
            field=models.CharField(
                blank=True,
                choices=[
                    ("vir", "Virement Bancaire"),
                    ("esp", "Espéce"),
                    ("chq", "Chéque"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="products",
            name="type_tarifcation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("a", "Année"),
                    ("h", "Horaire"),
                    ("j", "Jour"),
                    ("m", "Mois"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="type_profile",
            field=models.CharField(
                blank=True,
                choices=[("adm", "Administrateur"), ("ven", "Vendeurs")],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="rappels",
            name="etat",
            field=models.CharField(
                blank=True,
                choices=[
                    ("att", "En attente"),
                    ("enc", "En cours"),
                    ("ann", "Annuler"),
                    ("fin", "Terminer"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="rappels",
            name="priority",
            field=models.CharField(
                blank=True,
                choices=[("lo", "Basse"), ("he", "Haute"), ("me", "Medium")],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="rappels",
            name="type_rappel",
            field=models.CharField(
                blank=True,
                choices=[
                    ("tel", "Appel téléphonique"),
                    ("mes", "Message"),
                    ("ema", "Email"),
                ],
                max_length=3,
                null=True,
            ),
        ),
    ]
