# Generated by Django 5.0.7 on 2024-09-18 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commercial", "0076_categorie_produit_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clients",
            name="type_client",
            field=models.CharField(
                blank=True,
                choices=[("par", "Particulier"), ("ent", "Entreprise")],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="devis",
            name="delai_paiement",
            field=models.CharField(
                blank=True,
                choices=[
                    ("imm", "Immédiat"),
                    ("rec", "A réception"),
                    ("30j", "A 30 jours"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="devis",
            name="etat",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ter", "Terminer"),
                    ("bro", "Brouillon"),
                    ("fac", "A facturé"),
                    ("ann", "Annulé"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="devis",
            name="mode_paiement",
            field=models.CharField(
                blank=True,
                choices=[
                    ("vir", "Virement Bancaire"),
                    ("chq", "Chéque"),
                    ("esp", "Espéce"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="facture",
            name="delai_paiement",
            field=models.CharField(
                blank=True,
                choices=[
                    ("imm", "Immédiat"),
                    ("rec", "A réception"),
                    ("30j", "A 30 jours"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="facture",
            name="etat",
            field=models.CharField(
                blank=True,
                choices=[("ter", "Terminer"), ("bro", "Brouillon")],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="facture",
            name="mode_paiement",
            field=models.CharField(
                blank=True,
                choices=[
                    ("vir", "Virement Bancaire"),
                    ("chq", "Chéque"),
                    ("esp", "Espéce"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="facture_avoir",
            name="etat",
            field=models.CharField(
                blank=True,
                choices=[("ter", "Terminer"), ("bro", "Brouillon")],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="generalsettings",
            name="devise",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AGO", "Angola"),
                    ("AFG", "Afghanistan"),
                    ("AND", "Andorre"),
                    ("ZAF", "Afrique du Sud"),
                    ("ALB", "Albanie"),
                    ("DEU", "Allemagne"),
                    ("ATG", "Antigua-et-Barbuda"),
                    ("DZA", "Algérie"),
                    ("SAU", "Arabie Saoudite"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="mouvements_produit",
            name="type_mouvement",
            field=models.CharField(
                blank=True,
                choices=[("sor", "Sortie"), ("ent", "Entrée")],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="paiementclient",
            name="mode_paiement",
            field=models.CharField(
                blank=True,
                choices=[
                    ("vir", "Virement Bancaire"),
                    ("chq", "Chéque"),
                    ("esp", "Espéce"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="products",
            name="categorie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="commercial.categorie_produit",
            ),
        ),
        migrations.AlterField(
            model_name="products",
            name="type_produit",
            field=models.CharField(
                blank=True,
                choices=[("pro", "Produit"), ("srv", "Service")],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="products",
            name="type_tarifcation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("m", "Mois"),
                    ("h", "Horaire"),
                    ("a", "Année"),
                    ("j", "Jour"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="type_profile",
            field=models.CharField(
                blank=True,
                choices=[("ven", "Vendeurs"), ("adm", "Administrateur")],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="prospects",
            name="type_prospect",
            field=models.CharField(
                blank=True,
                choices=[("par", "Particulier"), ("ent", "Entreprise")],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="rappels",
            name="etat",
            field=models.CharField(
                blank=True,
                choices=[
                    ("enc", "En cours"),
                    ("fin", "Terminer"),
                    ("ann", "Annuler"),
                    ("att", "En attente"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="rappels",
            name="type_rappel",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mes", "Message"),
                    ("tel", "Appel téléphonique"),
                    ("ema", "Email"),
                ],
                max_length=3,
                null=True,
            ),
        ),
    ]
