# Generated by Django 5.0.7 on 2024-09-18 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "commercial",
            "0077_alter_clients_type_client_alter_devis_delai_paiement_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="tva",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="clients",
            name="type_client",
            field=models.CharField(
                blank=True,
                choices=[("ent", "Entreprise"), ("par", "Particulier")],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="devis",
            name="etat",
            field=models.CharField(
                blank=True,
                choices=[
                    ("fac", "A facturé"),
                    ("bro", "Brouillon"),
                    ("ann", "Annulé"),
                    ("ter", "Terminer"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="devis",
            name="mode_paiement",
            field=models.CharField(
                blank=True,
                choices=[
                    ("vir", "Virement Bancaire"),
                    ("esp", "Espéce"),
                    ("chq", "Chéque"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="facture",
            name="etat",
            field=models.CharField(
                blank=True,
                choices=[("bro", "Brouillon"), ("ter", "Terminer")],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="facture",
            name="mode_paiement",
            field=models.CharField(
                blank=True,
                choices=[
                    ("vir", "Virement Bancaire"),
                    ("esp", "Espéce"),
                    ("chq", "Chéque"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="facture_avoir",
            name="etat",
            field=models.CharField(
                blank=True,
                choices=[("bro", "Brouillon"), ("ter", "Terminer")],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="generalsettings",
            name="devise",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DEU", "Allemagne"),
                    ("SAU", "Arabie Saoudite"),
                    ("AGO", "Angola"),
                    ("AFG", "Afghanistan"),
                    ("ATG", "Antigua-et-Barbuda"),
                    ("ZAF", "Afrique du Sud"),
                    ("ALB", "Albanie"),
                    ("AND", "Andorre"),
                    ("DZA", "Algérie"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="mouvements_produit",
            name="type_mouvement",
            field=models.CharField(
                blank=True,
                choices=[("ent", "Entrée"), ("sor", "Sortie")],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="paiementclient",
            name="mode_paiement",
            field=models.CharField(
                blank=True,
                choices=[
                    ("vir", "Virement Bancaire"),
                    ("esp", "Espéce"),
                    ("chq", "Chéque"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="products",
            name="type_produit",
            field=models.CharField(
                blank=True,
                choices=[("srv", "Service"), ("pro", "Produit")],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="products",
            name="type_tarifcation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("j", "Jour"),
                    ("h", "Horaire"),
                    ("m", "Mois"),
                    ("a", "Année"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="prospects",
            name="type_prospect",
            field=models.CharField(
                blank=True,
                choices=[("ent", "Entreprise"), ("par", "Particulier")],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="rappels",
            name="etat",
            field=models.CharField(
                blank=True,
                choices=[
                    ("enc", "En cours"),
                    ("att", "En attente"),
                    ("ann", "Annuler"),
                    ("fin", "Terminer"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="rappels",
            name="priority",
            field=models.CharField(
                blank=True,
                choices=[("he", "Haute"), ("lo", "Basse"), ("me", "Medium")],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="rappels",
            name="type_rappel",
            field=models.CharField(
                blank=True,
                choices=[
                    ("tel", "Appel téléphonique"),
                    ("ema", "Email"),
                    ("mes", "Message"),
                ],
                max_length=3,
                null=True,
            ),
        ),
    ]
