# Generated by Django 5.0.7 on 2024-09-18 11:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "commercial",
            "0078_tva_user_alter_clients_type_client_alter_devis_etat_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="tva",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tva",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="devis",
            name="delai_paiement",
            field=models.CharField(
                blank=True,
                choices=[
                    ("rec", "A réception"),
                    ("imm", "Immédiat"),
                    ("30j", "A 30 jours"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="devis",
            name="etat",
            field=models.CharField(
                blank=True,
                choices=[
                    ("fac", "A facturé"),
                    ("ann", "Annulé"),
                    ("ter", "Terminer"),
                    ("bro", "Brouillon"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="devis",
            name="mode_paiement",
            field=models.CharField(
                blank=True,
                choices=[
                    ("esp", "Espéce"),
                    ("vir", "Virement Bancaire"),
                    ("chq", "Chéque"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="facture",
            name="delai_paiement",
            field=models.CharField(
                blank=True,
                choices=[
                    ("rec", "A réception"),
                    ("imm", "Immédiat"),
                    ("30j", "A 30 jours"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="facture",
            name="etat",
            field=models.CharField(
                blank=True,
                choices=[("ter", "Terminer"), ("bro", "Brouillon")],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="facture",
            name="mode_paiement",
            field=models.CharField(
                blank=True,
                choices=[
                    ("esp", "Espéce"),
                    ("vir", "Virement Bancaire"),
                    ("chq", "Chéque"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="facture_avoir",
            name="etat",
            field=models.CharField(
                blank=True,
                choices=[("ter", "Terminer"), ("bro", "Brouillon")],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="generalsettings",
            name="devise",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AGO", "Angola"),
                    ("ALB", "Albanie"),
                    ("AND", "Andorre"),
                    ("DEU", "Allemagne"),
                    ("ZAF", "Afrique du Sud"),
                    ("AFG", "Afghanistan"),
                    ("SAU", "Arabie Saoudite"),
                    ("DZA", "Algérie"),
                    ("ATG", "Antigua-et-Barbuda"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="mouvements_produit",
            name="type_mouvement",
            field=models.CharField(
                blank=True,
                choices=[("sor", "Sortie"), ("ent", "Entrée")],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="paiementclient",
            name="mode_paiement",
            field=models.CharField(
                blank=True,
                choices=[
                    ("esp", "Espéce"),
                    ("vir", "Virement Bancaire"),
                    ("chq", "Chéque"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="products",
            name="type_produit",
            field=models.CharField(
                blank=True,
                choices=[("pro", "Produit"), ("srv", "Service")],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="products",
            name="type_tarifcation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("a", "Année"),
                    ("h", "Horaire"),
                    ("j", "Jour"),
                    ("m", "Mois"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="rappels",
            name="etat",
            field=models.CharField(
                blank=True,
                choices=[
                    ("att", "En attente"),
                    ("ann", "Annuler"),
                    ("enc", "En cours"),
                    ("fin", "Terminer"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="rappels",
            name="priority",
            field=models.CharField(
                blank=True,
                choices=[("lo", "Basse"), ("me", "Medium"), ("he", "Haute")],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="rappels",
            name="type_rappel",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ema", "Email"),
                    ("mes", "Message"),
                    ("tel", "Appel téléphonique"),
                ],
                max_length=3,
                null=True,
            ),
        ),
    ]
