# Generated by Django 5.0.7 on 2024-09-18 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commercial", "0079_tva_created_at_tva_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clients",
            name="type_client",
            field=models.CharField(
                blank=True,
                choices=[("par", "Particulier"), ("ent", "Entreprise")],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="devis",
            name="delai_paiement",
            field=models.CharField(
                blank=True,
                choices=[
                    ("imm", "Immédiat"),
                    ("rec", "A réception"),
                    ("30j", "A 30 jours"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="devis",
            name="etat",
            field=models.CharField(
                blank=True,
                choices=[
                    ("bro", "Brouillon"),
                    ("fac", "A facturé"),
                    ("ann", "Annulé"),
                    ("ter", "Terminer"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="devis",
            name="mode_paiement",
            field=models.CharField(
                blank=True,
                choices=[
                    ("vir", "Virement Bancaire"),
                    ("chq", "Chéque"),
                    ("esp", "Espéce"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="facture",
            name="delai_paiement",
            field=models.CharField(
                blank=True,
                choices=[
                    ("imm", "Immédiat"),
                    ("rec", "A réception"),
                    ("30j", "A 30 jours"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="facture",
            name="etat",
            field=models.CharField(
                blank=True,
                choices=[("bro", "Brouillon"), ("ter", "Terminer")],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="facture",
            name="mode_paiement",
            field=models.CharField(
                blank=True,
                choices=[
                    ("vir", "Virement Bancaire"),
                    ("chq", "Chéque"),
                    ("esp", "Espéce"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="facture_avoir",
            name="etat",
            field=models.CharField(
                blank=True,
                choices=[("bro", "Brouillon"), ("ter", "Terminer")],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="generalsettings",
            name="devise",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SAU", "Arabie Saoudite"),
                    ("AFG", "Afghanistan"),
                    ("ATG", "Antigua-et-Barbuda"),
                    ("AND", "Andorre"),
                    ("AGO", "Angola"),
                    ("DEU", "Allemagne"),
                    ("DZA", "Algérie"),
                    ("ALB", "Albanie"),
                    ("ZAF", "Afrique du Sud"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="paiementclient",
            name="mode_paiement",
            field=models.CharField(
                blank=True,
                choices=[
                    ("vir", "Virement Bancaire"),
                    ("chq", "Chéque"),
                    ("esp", "Espéce"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="products",
            name="type_tarifcation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("j", "Jour"),
                    ("h", "Horaire"),
                    ("m", "Mois"),
                    ("a", "Année"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="type_profile",
            field=models.CharField(
                blank=True,
                choices=[("adm", "Administrateur"), ("ven", "Vendeurs")],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="prospects",
            name="type_prospect",
            field=models.CharField(
                blank=True,
                choices=[("par", "Particulier"), ("ent", "Entreprise")],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="rappels",
            name="etat",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ann", "Annuler"),
                    ("att", "En attente"),
                    ("enc", "En cours"),
                    ("fin", "Terminer"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="rappels",
            name="priority",
            field=models.CharField(
                blank=True,
                choices=[("lo", "Basse"), ("he", "Haute"), ("me", "Medium")],
                max_length=2,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="Bons_livraison",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(blank=True, max_length=1000, null=True)),
                (
                    "montant_total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=1000, null=True
                    ),
                ),
                (
                    "montant_paye",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=1000, null=True
                    ),
                ),
                (
                    "montant_restant",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=1000, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fournisseur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="commercial.fournisseurs",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Bon de livraison",
                "verbose_name_plural": "Bons de livraison",
            },
        ),
    ]
