# Generated by Django 5.0.7 on 2024-09-19 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commercial", "0081_alter_devis_etat_alter_devis_mode_paiement_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lignes_BonCommande",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="bons_livraison",
            name="date_du_bon",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bons_livraison",
            name="lieu_livraison",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="bons_livraison",
            name="observation",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="clients",
            name="type_client",
            field=models.CharField(
                blank=True,
                choices=[("ent", "Entreprise"), ("par", "Particulier")],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="devis",
            name="etat",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ann", "Annulé"),
                    ("fac", "A facturé"),
                    ("bro", "Brouillon"),
                    ("ter", "Terminer"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="devis",
            name="mode_paiement",
            field=models.CharField(
                blank=True,
                choices=[
                    ("vir", "Virement Bancaire"),
                    ("chq", "Chéque"),
                    ("esp", "Espéce"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="facture",
            name="etat",
            field=models.CharField(
                blank=True,
                choices=[("bro", "Brouillon"), ("ter", "Terminer")],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="facture",
            name="mode_paiement",
            field=models.CharField(
                blank=True,
                choices=[
                    ("vir", "Virement Bancaire"),
                    ("chq", "Chéque"),
                    ("esp", "Espéce"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="facture_avoir",
            name="etat",
            field=models.CharField(
                blank=True,
                choices=[("bro", "Brouillon"), ("ter", "Terminer")],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="generalsettings",
            name="devise",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ZAF", "Afrique du Sud"),
                    ("DEU", "Allemagne"),
                    ("ATG", "Antigua-et-Barbuda"),
                    ("DZA", "Algérie"),
                    ("ALB", "Albanie"),
                    ("SAU", "Arabie Saoudite"),
                    ("AFG", "Afghanistan"),
                    ("AGO", "Angola"),
                    ("AND", "Andorre"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="paiementclient",
            name="mode_paiement",
            field=models.CharField(
                blank=True,
                choices=[
                    ("vir", "Virement Bancaire"),
                    ("chq", "Chéque"),
                    ("esp", "Espéce"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="products",
            name="type_produit",
            field=models.CharField(
                blank=True,
                choices=[("srv", "Service"), ("pro", "Produit")],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="products",
            name="type_tarifcation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("m", "Mois"),
                    ("j", "Jour"),
                    ("h", "Horaire"),
                    ("a", "Année"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="prospects",
            name="type_prospect",
            field=models.CharField(
                blank=True,
                choices=[("ent", "Entreprise"), ("par", "Particulier")],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="rappels",
            name="etat",
            field=models.CharField(
                blank=True,
                choices=[
                    ("enc", "En cours"),
                    ("fin", "Terminer"),
                    ("ann", "Annuler"),
                    ("att", "En attente"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="rappels",
            name="priority",
            field=models.CharField(
                blank=True,
                choices=[("me", "Medium"), ("lo", "Basse"), ("he", "Haute")],
                max_length=2,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="Bons_commande",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(blank=True, max_length=1000, null=True)),
                ("date_du_bon", models.DateField(blank=True, null=True)),
                ("date_livraison", models.DateField(blank=True, null=True)),
                ("ref_devis", models.CharField(blank=True, max_length=1000, null=True)),
                (
                    "observation",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Bon de commande",
                "verbose_name_plural": "Bons de commande",
            },
        ),
    ]
