# Generated by Django 5.0.7 on 2024-09-19 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commercial", "0082_lignes_boncommande_bons_livraison_date_du_bon_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bons_commande",
            name="fournisseur",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="commercial.fournisseurs",
            ),
        ),
        migrations.AlterField(
            model_name="clients",
            name="type_client",
            field=models.CharField(
                blank=True,
                choices=[("par", "Particulier"), ("ent", "Entreprise")],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="devis",
            name="delai_paiement",
            field=models.CharField(
                blank=True,
                choices=[
                    ("30j", "A 30 jours"),
                    ("imm", "Immédiat"),
                    ("rec", "A réception"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="devis",
            name="etat",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ter", "Terminer"),
                    ("fac", "A facturé"),
                    ("ann", "Annulé"),
                    ("bro", "Brouillon"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="devis",
            name="mode_paiement",
            field=models.CharField(
                blank=True,
                choices=[
                    ("esp", "Espéce"),
                    ("chq", "Chéque"),
                    ("vir", "Virement Bancaire"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="facture",
            name="delai_paiement",
            field=models.CharField(
                blank=True,
                choices=[
                    ("30j", "A 30 jours"),
                    ("imm", "Immédiat"),
                    ("rec", "A réception"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="facture",
            name="etat",
            field=models.CharField(
                blank=True,
                choices=[("ter", "Terminer"), ("bro", "Brouillon")],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="facture",
            name="mode_paiement",
            field=models.CharField(
                blank=True,
                choices=[
                    ("esp", "Espéce"),
                    ("chq", "Chéque"),
                    ("vir", "Virement Bancaire"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="facture_avoir",
            name="etat",
            field=models.CharField(
                blank=True,
                choices=[("ter", "Terminer"), ("bro", "Brouillon")],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="generalsettings",
            name="devise",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AGO", "Angola"),
                    ("ZAF", "Afrique du Sud"),
                    ("AFG", "Afghanistan"),
                    ("DZA", "Algérie"),
                    ("DEU", "Allemagne"),
                    ("ALB", "Albanie"),
                    ("AND", "Andorre"),
                    ("SAU", "Arabie Saoudite"),
                    ("ATG", "Antigua-et-Barbuda"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="mouvements_produit",
            name="type_mouvement",
            field=models.CharField(
                blank=True,
                choices=[("sor", "Sortie"), ("ent", "Entrée")],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="paiementclient",
            name="mode_paiement",
            field=models.CharField(
                blank=True,
                choices=[
                    ("esp", "Espéce"),
                    ("chq", "Chéque"),
                    ("vir", "Virement Bancaire"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="products",
            name="type_tarifcation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("a", "Année"),
                    ("m", "Mois"),
                    ("h", "Horaire"),
                    ("j", "Jour"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="prospects",
            name="type_prospect",
            field=models.CharField(
                blank=True,
                choices=[("par", "Particulier"), ("ent", "Entreprise")],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="rappels",
            name="etat",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ann", "Annuler"),
                    ("enc", "En cours"),
                    ("fin", "Terminer"),
                    ("att", "En attente"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="rappels",
            name="priority",
            field=models.CharField(
                blank=True,
                choices=[("lo", "Basse"), ("he", "Haute"), ("me", "Medium")],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="rappels",
            name="type_rappel",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ema", "Email"),
                    ("mes", "Message"),
                    ("tel", "Appel téléphonique"),
                ],
                max_length=3,
                null=True,
            ),
        ),
    ]
