# Generated by Django 5.0.7 on 2024-09-19 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "commercial",
            "0083_bons_commande_fournisseur_alter_clients_type_client_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="bons_commande",
            name="etat",
            field=models.CharField(
                blank=True,
                choices=[("ann", "Annuler"), ("val", "Valider"), ("bro", "Brouillon")],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="devis",
            name="delai_paiement",
            field=models.CharField(
                blank=True,
                choices=[
                    ("imm", "Immédiat"),
                    ("30j", "A 30 jours"),
                    ("rec", "A réception"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="devis",
            name="etat",
            field=models.CharField(
                blank=True,
                choices=[
                    ("fac", "A facturé"),
                    ("ann", "Annulé"),
                    ("bro", "Brouillon"),
                    ("ter", "Terminer"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="devis",
            name="mode_paiement",
            field=models.CharField(
                blank=True,
                choices=[
                    ("vir", "Virement Bancaire"),
                    ("chq", "Chéque"),
                    ("esp", "Espéce"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="facture",
            name="delai_paiement",
            field=models.CharField(
                blank=True,
                choices=[
                    ("imm", "Immédiat"),
                    ("30j", "A 30 jours"),
                    ("rec", "A réception"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="facture",
            name="mode_paiement",
            field=models.CharField(
                blank=True,
                choices=[
                    ("vir", "Virement Bancaire"),
                    ("chq", "Chéque"),
                    ("esp", "Espéce"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="generalsettings",
            name="devise",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DEU", "Allemagne"),
                    ("ATG", "Antigua-et-Barbuda"),
                    ("ZAF", "Afrique du Sud"),
                    ("DZA", "Algérie"),
                    ("SAU", "Arabie Saoudite"),
                    ("AND", "Andorre"),
                    ("AFG", "Afghanistan"),
                    ("AGO", "Angola"),
                    ("ALB", "Albanie"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="paiementclient",
            name="mode_paiement",
            field=models.CharField(
                blank=True,
                choices=[
                    ("vir", "Virement Bancaire"),
                    ("chq", "Chéque"),
                    ("esp", "Espéce"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="products",
            name="type_produit",
            field=models.CharField(
                blank=True,
                choices=[("pro", "Produit"), ("srv", "Service")],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="products",
            name="type_tarifcation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("a", "Année"),
                    ("j", "Jour"),
                    ("m", "Mois"),
                    ("h", "Horaire"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="type_profile",
            field=models.CharField(
                blank=True,
                choices=[("adm", "Administrateur"), ("ven", "Vendeurs")],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="rappels",
            name="etat",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ann", "Annuler"),
                    ("att", "En attente"),
                    ("fin", "Terminer"),
                    ("enc", "En cours"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="rappels",
            name="type_rappel",
            field=models.CharField(
                blank=True,
                choices=[
                    ("tel", "Appel téléphonique"),
                    ("ema", "Email"),
                    ("mes", "Message"),
                ],
                max_length=3,
                null=True,
            ),
        ),
    ]
