# Generated by Django 5.0.7 on 2024-09-21 10:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "commercial",
            "0085_alter_bons_commande_etat_alter_clients_type_client_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lignes_boncommande",
            options={
                "verbose_name": "Ligne bon de commande",
                "verbose_name_plural": "Lignes bon de commande",
            },
        ),
        migrations.AddField(
            model_name="lignes_boncommande",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lignes_boncommande",
            name="produit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="commercial.products",
            ),
        ),
        migrations.AddField(
            model_name="lignes_boncommande",
            name="qty",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="lignes_boncommande",
            name="ref_commande",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="commercial.bons_commande",
            ),
        ),
        migrations.AddField(
            model_name="lignes_boncommande",
            name="total",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="lignes_boncommande",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="lignes_boncommande",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="devis",
            name="delai_paiement",
            field=models.CharField(
                blank=True,
                choices=[
                    ("rec", "A réception"),
                    ("imm", "Immédiat"),
                    ("30j", "A 30 jours"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="devis",
            name="etat",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ann", "Annulé"),
                    ("bro", "Brouillon"),
                    ("ter", "Terminer"),
                    ("fac", "A facturé"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="devis",
            name="mode_paiement",
            field=models.CharField(
                blank=True,
                choices=[
                    ("vir", "Virement Bancaire"),
                    ("esp", "Espéce"),
                    ("chq", "Chéque"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="facture",
            name="delai_paiement",
            field=models.CharField(
                blank=True,
                choices=[
                    ("rec", "A réception"),
                    ("imm", "Immédiat"),
                    ("30j", "A 30 jours"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="facture",
            name="etat",
            field=models.CharField(
                blank=True,
                choices=[("ter", "Terminer"), ("bro", "Brouillon")],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="facture",
            name="mode_paiement",
            field=models.CharField(
                blank=True,
                choices=[
                    ("vir", "Virement Bancaire"),
                    ("esp", "Espéce"),
                    ("chq", "Chéque"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="facture_avoir",
            name="etat",
            field=models.CharField(
                blank=True,
                choices=[("ter", "Terminer"), ("bro", "Brouillon")],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="generalsettings",
            name="devise",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ALB", "Albanie"),
                    ("AND", "Andorre"),
                    ("AGO", "Angola"),
                    ("DZA", "Algérie"),
                    ("AFG", "Afghanistan"),
                    ("ZAF", "Afrique du Sud"),
                    ("SAU", "Arabie Saoudite"),
                    ("ATG", "Antigua-et-Barbuda"),
                    ("DEU", "Allemagne"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="paiementclient",
            name="mode_paiement",
            field=models.CharField(
                blank=True,
                choices=[
                    ("vir", "Virement Bancaire"),
                    ("esp", "Espéce"),
                    ("chq", "Chéque"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="products",
            name="type_tarifcation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("m", "Mois"),
                    ("h", "Horaire"),
                    ("j", "Jour"),
                    ("a", "Année"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="type_profile",
            field=models.CharField(
                blank=True,
                choices=[("adm", "Administrateur"), ("ven", "Vendeurs")],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="rappels",
            name="etat",
            field=models.CharField(
                blank=True,
                choices=[
                    ("enc", "En cours"),
                    ("ann", "Annuler"),
                    ("fin", "Terminer"),
                    ("att", "En attente"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="rappels",
            name="priority",
            field=models.CharField(
                blank=True,
                choices=[("me", "Medium"), ("he", "Haute"), ("lo", "Basse")],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="rappels",
            name="type_rappel",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mes", "Message"),
                    ("ema", "Email"),
                    ("tel", "Appel téléphonique"),
                ],
                max_length=3,
                null=True,
            ),
        ),
    ]
