# Generated by Django 4.2.16 on 2024-09-26 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0086_alter_lignes_boncommande_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bons_livraison',
            name='fournisseur',
        ),
        migrations.RemoveField(
            model_name='bons_livraison',
            name='montant_paye',
        ),
        migrations.RemoveField(
            model_name='bons_livraison',
            name='montant_restant',
        ),
        migrations.RemoveField(
            model_name='bons_livraison',
            name='montant_total',
        ),
        migrations.AddField(
            model_name='bons_livraison',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commercial.clients'),
        ),
        migrations.AddField(
            model_name='bons_livraison',
            name='ref_commande_client',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='is_delivred',
            field=models.CharField(blank=True, default=0, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='ref_bon_livraison',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commercial.bons_livraison'),
        ),
        migrations.AlterField(
            model_name='bons_commande',
            name='etat',
            field=models.CharField(blank=True, choices=[('ann', 'Annuler'), ('bro', 'Brouillon'), ('val', 'Valider')], default='bro', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='type_client',
            field=models.CharField(blank=True, choices=[('par', 'Particulier'), ('ent', 'Entreprise')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='delai_paiement',
            field=models.CharField(blank=True, choices=[('30j', 'A 30 jours'), ('rec', 'A réception'), ('imm', 'Immédiat')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='etat',
            field=models.CharField(blank=True, choices=[('ann', 'Annulé'), ('bro', 'Brouillon'), ('fac', 'A facturé'), ('ter', 'Terminer')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('esp', 'Espéce'), ('chq', 'Chéque'), ('vir', 'Virement Bancaire')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='delai_paiement',
            field=models.CharField(blank=True, choices=[('30j', 'A 30 jours'), ('rec', 'A réception'), ('imm', 'Immédiat')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='etat',
            field=models.CharField(blank=True, choices=[('bro', 'Brouillon'), ('ter', 'Terminer')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('esp', 'Espéce'), ('chq', 'Chéque'), ('vir', 'Virement Bancaire')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='facture_avoir',
            name='etat',
            field=models.CharField(blank=True, choices=[('bro', 'Brouillon'), ('ter', 'Terminer')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='devise',
            field=models.CharField(blank=True, choices=[('DZA', 'Algérie'), ('ATG', 'Antigua-et-Barbuda'), ('ZAF', 'Afrique du Sud'), ('DEU', 'Allemagne'), ('AGO', 'Angola'), ('SAU', 'Arabie Saoudite'), ('ALB', 'Albanie'), ('AND', 'Andorre'), ('AFG', 'Afghanistan')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='mouvements_produit',
            name='type_mouvement',
            field=models.CharField(blank=True, choices=[('sor', 'Sortie'), ('ent', 'Entrée')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='paiementclient',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('esp', 'Espéce'), ('chq', 'Chéque'), ('vir', 'Virement Bancaire')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='type_produit',
            field=models.CharField(blank=True, choices=[('pro', 'Produit'), ('srv', 'Service')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='type_tarifcation',
            field=models.CharField(blank=True, choices=[('h', 'Horaire'), ('m', 'Mois'), ('a', 'Année'), ('j', 'Jour')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='prospects',
            name='type_prospect',
            field=models.CharField(blank=True, choices=[('par', 'Particulier'), ('ent', 'Entreprise')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rappels',
            name='etat',
            field=models.CharField(blank=True, choices=[('ann', 'Annuler'), ('att', 'En attente'), ('fin', 'Terminer'), ('enc', 'En cours')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='rappels',
            name='priority',
            field=models.CharField(blank=True, choices=[('lo', 'Basse'), ('he', 'Haute'), ('me', 'Medium')], max_length=2, null=True),
        ),
    ]
