# Generated by Django 4.2.16 on 2024-10-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0088_mouvements_produit_ref_commande_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignefactureavoir',
            name='rembourssement',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='delai_paiement',
            field=models.CharField(blank=True, choices=[('imm', 'Immédiat'), ('30j', 'A 30 jours'), ('rec', 'A réception')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='etat',
            field=models.CharField(blank=True, choices=[('fac', 'A facturé'), ('ter', 'Terminer'), ('bro', 'Brouillon'), ('ann', 'Annulé')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('vir', 'Virement Bancaire'), ('chq', 'Chéque'), ('esp', 'Espéce')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='delai_paiement',
            field=models.CharField(blank=True, choices=[('imm', 'Immédiat'), ('30j', 'A 30 jours'), ('rec', 'A réception')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='etat',
            field=models.CharField(blank=True, choices=[('val', 'Valider'), ('ter', 'Terminer'), ('bro', 'Brouillon')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('vir', 'Virement Bancaire'), ('chq', 'Chéque'), ('esp', 'Espéce')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='facture_avoir',
            name='etat',
            field=models.CharField(blank=True, choices=[('ter', 'Terminer'), ('bro', 'Brouillon')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='devise',
            field=models.CharField(blank=True, choices=[('AFG', 'Afghanistan'), ('AND', 'Andorre'), ('ATG', 'Antigua-et-Barbuda'), ('ALB', 'Albanie'), ('DEU', 'Allemagne'), ('DZA', 'Algérie'), ('AGO', 'Angola'), ('ZAF', 'Afrique du Sud'), ('SAU', 'Arabie Saoudite')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='mouvements_produit',
            name='type_mouvement',
            field=models.CharField(blank=True, choices=[('ent', 'Entrée'), ('sor', 'Sortie')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='paiementclient',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('vir', 'Virement Bancaire'), ('chq', 'Chéque'), ('esp', 'Espéce')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='type_produit',
            field=models.CharField(blank=True, choices=[('pro', 'Produit'), ('srv', 'Service')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='type_tarifcation',
            field=models.CharField(blank=True, choices=[('a', 'Année'), ('h', 'Horaire'), ('m', 'Mois'), ('j', 'Jour')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type_profile',
            field=models.CharField(blank=True, choices=[('ven', 'Vendeurs'), ('adm', 'Administrateur')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='rappels',
            name='etat',
            field=models.CharField(blank=True, choices=[('enc', 'En cours'), ('ann', 'Annuler'), ('fin', 'Terminer'), ('att', 'En attente')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='rappels',
            name='type_rappel',
            field=models.CharField(blank=True, choices=[('mes', 'Message'), ('tel', 'Appel téléphonique'), ('ema', 'Email')], max_length=3, null=True),
        ),
    ]
