# Generated by Django 4.2.16 on 2024-10-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0089_lignefactureavoir_rembourssement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='retourproduit',
            name='qty',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bons_commande',
            name='etat',
            field=models.CharField(blank=True, choices=[('ann', 'Annuler'), ('bro', 'Brouillon'), ('val', 'Valider')], default='bro', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='etat',
            field=models.CharField(blank=True, choices=[('bro', 'Brouillon'), ('ter', 'Terminer'), ('ann', 'Annulé'), ('fac', 'A facturé')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('vir', 'Virement Bancaire'), ('esp', 'Espéce'), ('chq', 'Chéque')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='etat',
            field=models.CharField(blank=True, choices=[('val', 'Valider'), ('bro', 'Brouillon'), ('ter', 'Terminer')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('vir', 'Virement Bancaire'), ('esp', 'Espéce'), ('chq', 'Chéque')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='facture_avoir',
            name='etat',
            field=models.CharField(blank=True, choices=[('bro', 'Brouillon'), ('ter', 'Terminer')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='devise',
            field=models.CharField(blank=True, choices=[('AFG', 'Afghanistan'), ('ZAF', 'Afrique du Sud'), ('DZA', 'Algérie'), ('ALB', 'Albanie'), ('AGO', 'Angola'), ('SAU', 'Arabie Saoudite'), ('AND', 'Andorre'), ('ATG', 'Antigua-et-Barbuda'), ('DEU', 'Allemagne')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='mouvements_produit',
            name='type_mouvement',
            field=models.CharField(blank=True, choices=[('sor', 'Sortie'), ('ent', 'Entrée')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='paiementclient',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('vir', 'Virement Bancaire'), ('esp', 'Espéce'), ('chq', 'Chéque')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='type_tarifcation',
            field=models.CharField(blank=True, choices=[('h', 'Horaire'), ('a', 'Année'), ('j', 'Jour'), ('m', 'Mois')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type_profile',
            field=models.CharField(blank=True, choices=[('adm', 'Administrateur'), ('ven', 'Vendeurs')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='rappels',
            name='etat',
            field=models.CharField(blank=True, choices=[('ann', 'Annuler'), ('att', 'En attente'), ('enc', 'En cours'), ('fin', 'Terminer')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='rappels',
            name='priority',
            field=models.CharField(blank=True, choices=[('he', 'Haute'), ('me', 'Medium'), ('lo', 'Basse')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='rappels',
            name='type_rappel',
            field=models.CharField(blank=True, choices=[('tel', 'Appel téléphonique'), ('ema', 'Email'), ('mes', 'Message')], max_length=3, null=True),
        ),
    ]
